In [27]:
import numpy as np

In [40]:
G0 = """
0 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0
0 1 0 1 0 0 0 0 1 0 1 0 1 0 0 1
0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0
1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0
1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1
1 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0
1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 1
0 0 1 1 0 0 0 1 1 0 1 1 0 0 0 1
"""
G = matrix(GF(2), [[int(e) for e in s.split()] for s in G0.split('\n') if s != ""])
G

[0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1]
[0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 0]
[1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0]
[0 0 0 1 0 0 0 0 1 0 1 0 0 1 1 0]
[0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1]
[0 0 1 1 0 1 0 0 1 0 0 0 0 0 1 1]
[0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 1]
[0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 1]

In [41]:
Y0 = "1 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0"
Y = vector(int(i) for i in Y0.split())
Y

(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0)

In [42]:
Gsp0 = G.rref()
Gsp0

[1 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1]
[0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 0]
[0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 1]
[0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1]
[0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0]
[0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 1]
[0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]

In [43]:
Gsp = copy(Gsp0)
Gsp.add_multiple_of_row(0, 7, 1)
Gsp.add_multiple_of_row(3, 7, 1)
Gsp.add_multiple_of_row(6, 7, 1)
Gsp.add_multiple_of_row(1, 6, 1)
Gsp.add_multiple_of_row(2, 6, 1)
Gsp.add_multiple_of_row(0, 5, 1)
Gsp.add_multiple_of_row(1, 5, 1)
Gsp.add_multiple_of_row(2, 5, 1)
Gsp.add_multiple_of_row(0, 4, 1)
Gsp.add_multiple_of_row(1, 4, 1)
Gsp.add_multiple_of_row(3, 4, 1)
Gsp.add_multiple_of_row(0, 2, 1)

Gsp.add_multiple_of_row(1, 3, 1)
Gsp.add_multiple_of_row(0, 1, 1)
Gsp

[1 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0]
[0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 0]
[0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1]
[0 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0]
[0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0]
[0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 1]
[0 0 0 0 0 0 1 0 1 1 1 0 1 1 0 1]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]

In [44]:
def doJ(colI, line):
    ll = list(line)
    f1 = ll.index(1)
    ll.reverse()
    l1 = len(ll) - 1 - ll.index(1)
    if f1 <= colI and colI < l1:
        return 1
    else:
        return 0
Vi = [sum([doJ(colI, i) for i in Gsp.rows()]) for colI in range(Gsp.ncols())]
[0] + Vi

[0, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 8, 7, 7, 6, 4, 0]

In [45]:
def gen_bits(n, *, i = 0, arr = []):
    if i == n:
        yield arr
        return
    yield from gen_bits(n, i=i+1, arr=arr+[1])
    yield from gen_bits(n, i=i+1, arr=arr+[0])

In [46]:
npy = np.array(Y)
bestVect, bestDist = None, None
for e in gen_bits(G.nrows()):
    v = vector(GF(2), e)
    r = v * G
    dist = np.sum(np.array(r) != npy)
    if bestDist is None or dist < bestDist:
        bestDist = dist
        bestVect = v
    elif dist == bestDist:
        print(f'also {v} with {dist}')
print(f'Found best {bestDist} on {bestVect}')
print(Y)
print(bestVect * G)
# print('(1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0)')

also (1, 0, 1, 1, 1, 0, 1, 0) with 4
Found best 2 on (1, 0, 1, 1, 1, 0, 0, 0)
(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0)
(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0)
